---
- name: Install Python, Pip, and execute incident response scripts
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Install Python and Pip
      raw: |
        apt-get update
        apt-get install -y python3 python3-pip

    - name: Install necessary Python packages
      pip:
        name: "{{ item }}"
        state: present
      with_items:
        - setuptools
        - wheel
        - requests
        - pillow
        - csv
        - shutil
        - requests

    - name: Create execution directory
      file:
        path: /home/apv/Documents/incident_response
        state: directory
        mode: '0755'

    - name: Transfer incident response scripts to target hosts
      copy:
        src: "{{ playbook_dir }}/incident_response_scripts"
        dest: /opt/incident_response
        mode: '0755'

    - name: Execute incident response scripts
      command: "/opt/incident_response/{{ item }}"
      with_items:
        - finalAPV.py
        - alertAPV.py
        # Add more script filenames as needed

    - name: Transfer incident response playbook to target hosts
      copy:
        src: "{{ playbook_dir }}/incident_response_playbook.md"
        dest: /opt/incident_response_playbook.md
        mode: '0644'

